appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NdJGo7yb7Vq1qwroY037xxDbxgr3o++cy5nykj4VrCiEEjbZE4D9B5SUrbMr8PGvdu8SUWLUhIfKQhZusreDMS8+1q3IGnoOE0K/YqFidYBHuL6htllu91DcAK9QwVh6Z1xfTg7udtRjM74bRXcY6H/04tm+ZMk9GGWcLSz3YGhKUeh2PmyQDSgiyvdMi+O9xu1473GYNFRm5icPCFf2lofLs6a9K2ozUk3x1+2GDxUXvwawqilDRpsaQIXq5nkrItpmwi5cepbP867AM2VfglePZQW5AL+c5DaMxqAyM5wZ0uOdRUd0Jt80QMRIIhyhdJ5ywXdrb4ihu3t+acj5GOxfSWVeZAIKOiw5zmUKsK3T9B8+4X3MVLI7xA/aWpyZunceK0ZU2uctm5NIe3ilug7uWx3Tc9nUhufoZvRS1huDrsdxwTE7MK/H6vcZ+IamJRm3xKRTnesU9uXmd6kZZTzPGHX3ZE8+Yx70YKRaQMS9CeidExiz9xQAWs7sr8GPoAnroAH6cwozvjMmvlebrU70HnXwd1jyyTAFNPO89mCm3robg5O52+JDiF1+GCd7l9YvybV2iKe+40fhpwaDryQ/NsEpgNHL5ExridWJwOzR0HcEKmiOIFb5pIz8Aic+w0//rGxIPe5E3c9wcCXqvCfrXyLOwMJXOh8AunLK3dk=}
