travis:
  secure:
    BINSTAR_TOKEN: Q3pP+bxdBR+XEWoJEbz38NOgV2MVGfoH6WByz/EhnECquHMXZBqMt0OPWOW3FkiGeX98+5dD3qtOQGBdNk1lULKo03tzgG1Q35VkXuZdIEFeGJ6et/HayIHZPEb1UzG0Zm3T0jHxPj1f6x3HuIwI4qYRn+TVUv2Q1EjSCuPF0vQ8Y0h5ScJoSIJRQGhAi/SU9DEUo0DaHDvN52PzWntZAoKd2pIFZvm+xSVrMblLvhEUi45b528rBShflzBbge5gmwoZvDb2srpldjpRaR3VOrOTDGrgSMYB5KQ+zv9yPXLiAowzBZoHPfhAbat1x114tgcXyCcEJgopJV9Wp4oAKubCdozQme/VJmSc6L6WzDbQHBkcHLTC+KvRhFHHobgc9x+J3T4nJIU4BXzkv13RRXqwAUIb1mt6U5gTTjneClAEp7YuRXJ6YWngQ6D8ukUn8piadPPFZMXfH/F+mRcdHJTSvSC9NeDIGc9honLQkBudBVMIIuSzLspVVyng1TuUFcnRFSXBuu7Cz0QeP/mAm91a3G0w3khm/Ij1W+sYk4CMc04/Pky60fTR9Szq9MJl5/WFdXfQjyjxf/utvTcOiqMBXt+ct8NxkgXNov4bStwmhPoygv2rPI/WE+6IxCDWgzVDVIlI0Li8IR9qAt5QfZDcYjICMN/Ps18bbmb5xmw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
