travis:
  secure:
    BINSTAR_TOKEN: C3rJTzBI9/bfubar6uu3i1fkLDvmslmTdB0alBHv0j9YCFoK7W9ibNX7iY1l/M7FJVouVRCZO0J1WscEkwMK5329DDq0nYqlmzeSSq2b/qCb3qcrE9+Q8qIdszxh9XjFAuMwOU9gI1mwWcDJpLIaSScsQDh0ge6tbcU5DRiaJ+DpSjzvG68E2ub/19iBSkGf0at5RHK4fMw/aokvUce6wIZOZaUMfnVdy+iNa5Ch0eOUwRBmwH1LXnzNHUm2rcEjcadNUvcNrEgJfb0WRtoiztgSeTLp4uLQtLkPQf+z6LlJdD6Osmu2inBx8cYORJWHsMa27rV0EUkRTNyfS+dMkT89SjFpJ3N8zgk3/FzUz0NWZVGmIDuU5mIQLR4usp/EJV1C6acJAOVBwujmpb8TqZThDkRD+q1TOKK44jdL6A2wMtsO7lC9C2vCsL30KI6CuD4BW8JfEHlLPpy8vM0B21jcT9TVe1Quvd1vAxyC9J5+vD0GgcwxyZ6G6xxwTc7cyXLpP7q+vAaDUo3GIryOFsSxwuf/MpGIz8i6IA74PafyiF8yb7XHg0wZmckg0Cswaq/rfh4AthfEdUdpB4zFg2KOfFWzuCyzOpRPCyys2evZ0S4F5HOIUEQ/cWvc8yh+ouIC7h9DclYQdJbUZtTkRCUjnH4eQCMPX9DIaOZwcWM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
